"""Add allowed_domains to widget_configs

Revision ID: 001c3ed9a1b2
Revises: 7a3b5d2e9f4a
Create Date: 2026-01-15 00:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = '001c3ed9a1b2'
down_revision: Union[str, None] = '7a3b5d2e9f4a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('widget_configs',
        sa.Column('allowed_domains', postgresql.ARRAY(sa.String()), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('widget_configs', 'allowed_domains')
    # ### end Alembic commands ###
