"""Add event_widgets table

Revision ID: 7a3b5d2e9f4a
Revises: f96e8e95c53c
Create Date: 2026-01-14 12:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7a3b5d2e9f4a'
down_revision: Union[str, None] = 'f96e8e95c53c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('event_widgets',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('event_id', sa.UUID(), nullable=False),
    sa.Column('widget_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['widget_id'], ['widget_configs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # Create index for faster lookups
    op.create_index('ix_event_widgets_event_id', 'event_widgets', ['event_id'], unique=False)
    op.create_index('ix_event_widgets_widget_id', 'event_widgets', ['widget_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_event_widgets_widget_id', table_name='event_widgets')
    op.drop_index('ix_event_widgets_event_id', table_name='event_widgets')
    op.drop_table('event_widgets')
    # ### end Alembic commands ###
