"""add_usage_count_to_api_keys

Revision ID: 11543332d763
Revises: 002d4ed8b2c3
Create Date: 2026-01-14 23:41:30.557215

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '11543332d763'
down_revision: Union[str, None] = '002d4ed8b2c3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('api_keys',
        sa.Column('usage_count', sa.Integer(), nullable=False, server_default='0')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('api_keys', 'usage_count')
    # ### end Alembic commands ###
