"""Add name and allowed_domains to api_keys

Revision ID: 002d4ed8b2c3
Revises: 001c3ed9a1b2
Create Date: 2026-01-15 01:30:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = '002d4ed8b2c3'
down_revision: Union[str, None] = '001c3ed9a1b2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Добавляем name с default значением для существующих записей
    op.add_column('api_keys',
        sa.Column('name', sa.String(), nullable=False, server_default='API Key')
    )
    # Добавляем allowed_domains
    op.add_column('api_keys',
        sa.Column('allowed_domains', postgresql.ARRAY(sa.String()), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('api_keys', 'allowed_domains')
    op.drop_column('api_keys', 'name')
    # ### end Alembic commands ###
