"""Add event_widgets table

Revision ID: 18ee50a155ea
Revises: 11543332d763
Create Date: 2026-01-15 12:14:37.180749

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '18ee50a155ea'
down_revision: Union[str, None] = '11543332d763'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_event_widgets_event_id', table_name='event_widgets')
    op.drop_index('ix_event_widgets_widget_id', table_name='event_widgets')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_event_widgets_widget_id', 'event_widgets', ['widget_id'], unique=False)
    op.create_index('ix_event_widgets_event_id', 'event_widgets', ['event_id'], unique=False)
    # ### end Alembic commands ###
